import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import {
  useMoralis,
  useEnsAddress,
  useMoralisWeb3Api,
  useMoralisWeb3ApiCall,
  useNFTBalances,
  useChain,
} from "react-moralis";
import { PlusCircleIcon } from "@heroicons/react/solid";

const Home: NextPage = () => {
  const [walletAddress, setWalletAddress] = useState({
    full: "",
    truncated: "",
  });

  const { switchNetwork, chainId, chain, account } = useChain();

  const {
    authenticate,
    logout,
    isAuthenticated,
    user,
    initialize,
    authError,
    hasAuthError,
  } = useMoralis();

  const { name: ensName, isLoading, error } = useEnsAddress(account || "");

  const { getNFTBalances, data: nfts, isFetching } = useNFTBalances();

  console.log({ chain, account });

  console.log({ ensName, isLoading });
  console.log({ user });
  console.log({ authError });
  console.log({ nfts });

  useEffect(() => {
    initialize();
  }, [initialize]);

  useEffect(() => {
    const full = account || "";
    /** Looks like 0x00...0000 */
    const truncated = full
      ? `${full.substring(0, 4)}...${full.substring(
          full.length - 4,
          full.length
        )}`
      : "";
    setWalletAddress({ full, truncated });
  }, [account]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="container flex items-center justify-between py-12">
        <h1 className="text-2xl font-sans">Web3</h1>
        <div className="font-mono text-right flex items-center space-x-4">
          {isAuthenticated ? (
            <>
              <div>
                <span className="block">{walletAddress.truncated}</span>
                <span className="block">Network: {chain?.name}</span>
              </div>
              <button
                onClick={() => logout()}
                className="bg-blue-900 px-4 py-3 border-2 border-blue-700 hover:bg-blue-600 rounded-full transition-colors duration-100"
              >
                <span className="block">Disconnect</span>
              </button>
            </>
          ) : (
            <div>
              <button
                onClick={() => authenticate()}
                className="bg-blue-900 px-4 py-3 border-2 border-blue-700 hover:bg-blue-600 rounded-full transition-colors duration-100"
              >
                Connect Wallet
              </button>
              {hasAuthError && authError?.code === 4001 ? (
                <span className="block text-xs text-red-400 mt-2">
                  User denied connection request.
                </span>
              ) : null}
            </div>
          )}
        </div>
      </header>

      <main className="container">
        <div className="card bg-neutral-800 rounded-2xl border-neutral-600 border-2 text-white p-6 flex flex-col md:flex-row items-center md:items-stretch flex-wrap max-w-3xl mx-auto">
          <div className="card-avatar w-4/12 relative">
            <a
              href="https://opensea.io/assets/0x3eff964d46c62be703d9a01ef720ba0479e79c3c/3329"
              target="_blank"
              rel="noreferrer"
              className="block rounded-xl overflow-hidden"
            >
              <img
                src={
                  nfts?.result
                    ? nfts.result[0]?.metadata?.image ||
                      nfts.result[0]?.metadata?.image_url
                    : null
                }
                alt=""
              />
            </a>
            <span className="block absolute bottom-2 left-0 -rotate-90 whitespace-nowrap origin-bottom-left text-xs uppercase font-semibold text-neutral-500">
              {nfts?.result ? nfts.result[0]?.metadata?.name : null}
            </span>
          </div>
          <div className="card-info w-8/12 flex flex-col justify-around md:pl-6">
            <div className="">
              <h3>Name</h3>
              <span>{ensName}</span>
            </div>

            <div className="">
              <h3>Website</h3>
              <span>
                {/* <a href="michaelmercer.xyz" target="_blank" rel="noreferrer"> */}
                None set
                {/* </a> */}
              </span>
            </div>

            <div className="">
              <h3>Wallet Address</h3>
              <span>
                <a
                  href={`${chain?.blockExplorerUrl}/address/${walletAddress.full}`}
                  target="_blank"
                  rel="noreferrer"
                  title={walletAddress.full}
                >
                  {walletAddress.full}
                </a>
              </span>
            </div>
          </div>
          <div className="card-collection w-full mt-6">
            <h3 className="mb-2">Featured Collection</h3>
            <div className="flex flex-wrap -mx-1">
              {nfts?.result
                ? nfts.result.map((n) => (
                    <div
                      key={`${n.token_address}-${n.token_id}`}
                      className="card-collection-item"
                    >
                      <a
                        href={`https://opensea.io/assets/${n.token_address}/${n.token_id}`}
                        target="_blank"
                        rel="noreferrer"
                      >
                        <img
                          src={n.metadata?.image || n.metadata?.image_url}
                          alt=""
                        />
                      </a>
                    </div>
                  ))
                : null}

              {[1, 2, 3, 4, 5].map((n, i) => {
                if (i + (nfts?.result?.length || 0) >= 5) return null;
                return (
                  <div key={`add-new-${n}`} className="card-collection-item">
                    <button>
                      <PlusCircleIcon />
                    </button>
                  </div>
                );
              })}

              <div className="card-collection-item">
                <button>
                  <PlusCircleIcon />
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

// https://lh3.googleusercontent.com/-7PJjPCc6GS7J-T_ZG4Ek5jVVdaDpVt4PJi0snEFj-IYGPNxeG7m87mz1LzSlnvvDQ6XsJfizUxSQIba8rdEcEY2c42ohlXLI73zSg=w325

export default Home;
