import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { useMoralis, useEnsAddress } from "react-moralis";
import { LogoutIcon, PlusCircleIcon } from "@heroicons/react/solid";

const testWallet = "0x0000000000000000000000000000000000000000";

const truncatedWallet = `${testWallet.substring(0, 4)}...${testWallet.substring(
  testWallet.length - 4,
  testWallet.length
)}`;

const Home: NextPage = () => {
  const {
    authenticate,
    logout,
    isAuthenticated,
    user,
    initialize,
    authError,
    hasAuthError,
  } = useMoralis();
  console.log(user);
  const { name, isLoading, error } = useEnsAddress(user?.id);
  console.log(authError, hasAuthError);

  useEffect(() => {
    initialize();
  }, [initialize]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <header className="container flex items-center justify-between py-12">
        <h1 className="text-2xl font-sans">Web3</h1>
        <div className="font-mono text-right flex items-center space-x-4">
          {isAuthenticated ? (
            <>
              <div>
                <span className="block">{truncatedWallet}</span>
                <span className="block">Network: Polygon</span>
              </div>
              <button
                onClick={logout}
                className="bg-blue-900 px-4 py-3 border-2 border-blue-700 hover:bg-blue-600 rounded-full transition-colors duration-100"
              >
                <span className="block">Disconnect</span>
              </button>
            </>
          ) : (
            <div>
              <button
                onClick={authenticate}
                className="bg-blue-900 px-4 py-3 border-2 border-blue-700 hover:bg-blue-600 rounded-full transition-colors duration-100"
              >
                Connect Wallet
              </button>
              {hasAuthError && authError?.code === 4001 ? (
                <span className="block text-xs text-red-400 mt-2">
                  User denied connection request.
                </span>
              ) : null}
            </div>
          )}
        </div>
      </header>

      <main className="container">
        <div className="card bg-neutral-800 rounded-2xl border-neutral-600 border-2 text-white p-6 flex flex-col md:flex-row items-center md:items-stretch flex-wrap">
          <div className="card-avatar w-4/12 relative">
            <a
              href="https://opensea.io/assets/0x3eff964d46c62be703d9a01ef720ba0479e79c3c/3329"
              target="_blank"
              rel="noreferrer"
              className="block rounded-xl overflow-hidden"
            >
              <img
                src="https://lh3.googleusercontent.com/NGSjNZkKImLpxMeKWbxEQY4Z8pyXCFuxwHGwMqLfaWR475ULAhQur_FqG_vQfPo9tP_5B0u55UhLdJk_C0Kin_k7GqFefNfPXtZNLQ=w351"
                alt=""
              />
            </a>
            <span className="block absolute bottom-2 left-0 -rotate-90 whitespace-nowrap origin-bottom-left text-xs uppercase font-semibold text-neutral-500">
              Tiki #3329
            </span>
          </div>
          <div className="card-info w-8/12 flex flex-col justify-around md:pl-6">
            <div className="">
              <h3>Name</h3>
              <span>michaelmercer.eth</span>
            </div>

            <div className="">
              <h3>Website</h3>
              <span>
                <a href="michaelmercer.xyz" target="_blank" rel="noreferrer">
                  michaelmercer.xyz
                </a>
              </span>
            </div>

            <div className="">
              <h3>Wallet Address</h3>
              <span>
                <a
                  href={`https://etherscan.io/address/${testWallet}`}
                  target="_blank"
                  rel="noreferrer"
                  title={testWallet}
                >
                  {testWallet}
                </a>
              </span>
            </div>
          </div>
          <div className="card-collection w-full mt-6">
            <h3 className="mb-2">Featured Collection</h3>
            <div className="flex flex-wrap -mx-1">
              <div className="card-collection-item">
                <a href="#">
                  <img
                    src="https://lh3.googleusercontent.com/DdG2ouup4GsEfpsY7H57jJyFhnAeNqF0bJ62UoiueoS0MGH5neGTEdTdr84U42Hv7DUiiunl3V3WabOl5QXwRShIMJhHrkKjJEmCDz4=w325"
                    alt=""
                  />
                </a>
              </div>

              <div className="card-collection-item">
                <a href="#">
                  <img
                    src="https://lh3.googleusercontent.com/DdG2ouup4GsEfpsY7H57jJyFhnAeNqF0bJ62UoiueoS0MGH5neGTEdTdr84U42Hv7DUiiunl3V3WabOl5QXwRShIMJhHrkKjJEmCDz4=w325"
                    alt=""
                  />
                </a>
              </div>

              <div className="card-collection-item">
                <a href="#">
                  <img
                    src="https://lh3.googleusercontent.com/DdG2ouup4GsEfpsY7H57jJyFhnAeNqF0bJ62UoiueoS0MGH5neGTEdTdr84U42Hv7DUiiunl3V3WabOl5QXwRShIMJhHrkKjJEmCDz4=w325"
                    alt=""
                  />
                </a>
              </div>

              <div className="card-collection-item">
                <a href="#">
                  <img
                    src="https://lh3.googleusercontent.com/DdG2ouup4GsEfpsY7H57jJyFhnAeNqF0bJ62UoiueoS0MGH5neGTEdTdr84U42Hv7DUiiunl3V3WabOl5QXwRShIMJhHrkKjJEmCDz4=w325"
                    alt=""
                  />
                </a>
              </div>

              <div className="card-collection-item">
                <a href="#">
                  <img
                    src="https://lh3.googleusercontent.com/DdG2ouup4GsEfpsY7H57jJyFhnAeNqF0bJ62UoiueoS0MGH5neGTEdTdr84U42Hv7DUiiunl3V3WabOl5QXwRShIMJhHrkKjJEmCDz4=w325"
                    alt=""
                  />
                </a>
              </div>

              <div className="card-collection-item">
                <button>
                  <PlusCircleIcon />
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

// https://lh3.googleusercontent.com/-7PJjPCc6GS7J-T_ZG4Ek5jVVdaDpVt4PJi0snEFj-IYGPNxeG7m87mz1LzSlnvvDQ6XsJfizUxSQIba8rdEcEY2c42ohlXLI73zSg=w325

export default Home;
