import type { NextPage } from "next";
import Head from "next/head";
// import { useMoralis } from "react-moralis";

const Home: NextPage = () => {
  // const { authenticate, isAuthenticated, user } = useMoralis();
  // console.log(user);

  // if (!isAuthenticated) {
  //   return (
  //     <div>
  //       <button onClick={() => authenticate()}>Authenticate</button>
  //     </div>
  //   );
  // }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
      </Head>

      <main className="container">
        <h1 className="text-2xl">Web3</h1>
      </main>
    </div>
  );
};

export default Home;
